### ISSUE TITLE
Replacing curly quotes with normal quotes

### ISSUE THREAD

**Issue by sbrichardson** [gajus/crack-json#2]
I noticed a lot of html/formatted docs use the special/curly quotes symbol. The parser will skip this JSON currently. 

```js
{“my_user_id” : “12345”} // curly quotes

{"my_user_id" : "12345"} // normal quotes
```

This resolves it naively, but it may need more logic to handle new lines or other cases.
I can do a PR but wanted to discuss first.

```js
let fixedSubject = subject.replace(/[\u201C\u201D]/g, '"')
```

---

Related from [StackOverflow - 9401312](https://stackoverflow.com/questions/9401312/how-to-replace-curly-quotation-marks-in-a-string-using-javascript)

> You might have to (or prefer to) use Unicode escapes:

```js
var goodQuotes = badQuotes.replace(/[\u2018\u2019]/g, "'");
That's for funny single quotes; the codes for double quotes are 201C and 201D.

edit — thus to completely replace all the fancy quotes:

var goodQuotes = badQuotes
  .replace(/[\u2018\u2019]/g, "'")
  .replace(/[\u201C\u201D]/g, '"');
```

**Comment by gajus** [comment]
Never seen this. If if you have such use case, just pre-process the input as you've suggested.

Crack JSON is for extracting valid JSON out of documents.

**Comment by sbrichardson** [comment]
No problem, here is one example for reference, I saw this issue when scraping these docs.

https://rest-docs.taplytics.com/#header-custom-data
